[package]
name = "RustyKalman"
version = "0.1.0"
authors = ["Tarun Kumar <trn3274@gmail.com>"]
edition = "2018"

[features]
default = ["std", "serde-serialize"]
std = ["nalgebra/std", "serde/std", "alga/std"]
serde-serialize = ["serde", "nalgebra/serde-serialize"]
compact = []

[dependencies]
nalgebra = { version = "0.17.2", default-features = false }
serde = { version = "~1.0", optional = true, default-features = false, features = ["derive"] }
typenum = "1.10.0"
alga = { version = "^0.8", optional = true, default-features = false }
